name=input("Enter name")
age=input("Enter age")
gender=input("Enter Gender")
college=input("Enter college name")
branch= input("Enter branch")
print('\n')
print("Name: ",name)
print("Age: ",age)
print("Gender: ",gender)
print("College: ",college)
print("Branch: ",branch)